import { defineArrayMember, defineField, defineType } from 'sanity';

const project = defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  groups: [
    { name: 'listing', title: 'Listing', default: true },
    { name: 'caseStudy', title: 'Case Study' },
    { name: 'media', title: 'Media' },
    { name: 'links', title: 'Links' },
    { name: 'ordering', title: 'Ordering' },
  ],
  initialValue: {
    featured: false,
    sortOrder: 100,
  },
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'listing',
      validation: (Rule) => Rule.required().max(100),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'listing',
      description: 'Used in the public case-study URL.',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'listing',
      options: {
        list: [
          { title: 'Security', value: 'Security' },
          {
            title: 'Solution Engineering',
            value: 'Solution Engineering',
          },
          { title: 'Cloud', value: 'Cloud' },
          { title: 'Web Development', value: 'Web Development' },
          { title: 'Product', value: 'Product' },
          { title: 'Research', value: 'Research' },
        ],
        layout: 'dropdown',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
      group: 'listing',
      rows: 4,
      description: 'The concise overview used on cards and in search results.',
      validation: (Rule) => Rule.required().max(280),
    }),
    defineField({
      name: 'projectDate',
      title: 'Project Date',
      type: 'date',
      group: 'listing',
      description: 'Use the most relevant completion or publication date.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'role',
      title: 'Role',
      type: 'string',
      group: 'listing',
      description: 'Your role or primary responsibility in this project.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'projectContext',
      title: 'Project Context',
      type: 'text',
      group: 'listing',
      rows: 3,
      description:
        'The client, organization, course, practice, or setting behind the work.',
      validation: (Rule) => Rule.required().max(320),
    }),
    defineField({
      name: 'duration',
      title: 'Duration',
      type: 'string',
      group: 'listing',
      description: 'For example, “6 weeks” or “Ongoing practice”.',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'technologies',
      title: 'Technologies and Methods',
      type: 'array',
      group: 'listing',
      of: [defineArrayMember({ type: 'string' })],
      options: { layout: 'tags' },
      validation: (Rule) => Rule.required().min(1).unique(),
    }),
    defineField({
      name: 'challenge',
      title: 'Challenge',
      type: 'text',
      group: 'caseStudy',
      rows: 7,
      description: 'The problem, constraints, and stakes that shaped the work.',
      validation: (Rule) => Rule.required().min(80),
    }),
    defineField({
      name: 'approach',
      title: 'Approach',
      type: 'array',
      group: 'caseStudy',
      description: 'Ordered steps that explain how you worked through it.',
      of: [
        defineArrayMember({
          name: 'approachStep',
          title: 'Approach Step',
          type: 'object',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              validation: (Rule) => Rule.required().max(80),
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'text',
              rows: 4,
              validation: (Rule) => Rule.required().min(40),
            }),
          ],
          preview: {
            select: { title: 'title', subtitle: 'description' },
          },
        }),
      ],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'solution',
      title: 'Solution',
      type: 'text',
      group: 'caseStudy',
      rows: 7,
      description: 'What you ultimately designed, built, or delivered.',
      validation: (Rule) => Rule.required().min(80),
    }),
    defineField({
      name: 'outcomes',
      title: 'Outcomes',
      type: 'array',
      group: 'caseStudy',
      of: [defineArrayMember({ type: 'string' })],
      validation: (Rule) => Rule.required().min(1).unique(),
    }),
    defineField({
      name: 'metrics',
      title: 'Measurable Results',
      type: 'array',
      group: 'caseStudy',
      description:
        'Optional evidence such as scale, speed, coverage, or reach.',
      of: [
        defineArrayMember({
          name: 'metric',
          title: 'Metric',
          type: 'object',
          fields: [
            defineField({
              name: 'value',
              title: 'Value',
              type: 'string',
              validation: (Rule) => Rule.required().max(32),
            }),
            defineField({
              name: 'label',
              title: 'Label',
              type: 'string',
              validation: (Rule) => Rule.required().max(100),
            }),
          ],
          preview: { select: { title: 'value', subtitle: 'label' } },
        }),
      ],
    }),
    defineField({
      name: 'learnings',
      title: 'Learnings and Reflections',
      type: 'array',
      group: 'caseStudy',
      of: [defineArrayMember({ type: 'string' })],
      validation: (Rule) => Rule.required().min(1).unique(),
    }),
    defineField({
      name: 'confidentialityNote',
      title: 'Confidentiality Note',
      type: 'text',
      group: 'caseStudy',
      rows: 3,
      description: 'Optional context for anonymized or NDA-sensitive work.',
      validation: (Rule) => Rule.max(240),
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alternative Text',
          type: 'string',
          validation: (Rule) => Rule.required().max(180),
        }),
        defineField({
          name: 'caption',
          title: 'Caption',
          type: 'string',
          validation: (Rule) => Rule.max(180),
        }),
      ],
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      group: 'media',
      of: [
        defineArrayMember({
          type: 'image',
          options: { hotspot: true },
          fields: [
            defineField({
              name: 'alt',
              title: 'Alternative Text',
              type: 'string',
              validation: (Rule) => Rule.required().max(180),
            }),
            defineField({
              name: 'caption',
              title: 'Caption',
              type: 'string',
              validation: (Rule) => Rule.max(180),
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'liveUrl',
      title: 'Live Project URL',
      type: 'url',
      group: 'links',
      validation: (Rule) => Rule.uri({ scheme: ['http', 'https'] }),
    }),
    defineField({
      name: 'repositoryUrl',
      title: 'Repository URL',
      type: 'url',
      group: 'links',
      validation: (Rule) => Rule.uri({ scheme: ['http', 'https'] }),
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      group: 'ordering',
      description:
        'Featured projects sort first. The first receives the lead card treatment.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sortOrder',
      title: 'Sort Order',
      type: 'number',
      group: 'ordering',
      description: 'Lower numbers appear first within the same group.',
      validation: (Rule) => Rule.required().integer().min(0),
    }),
  ],
  orderings: [
    {
      title: 'Portfolio order',
      name: 'portfolioOrder',
      by: [
        { field: 'featured', direction: 'desc' },
        { field: 'sortOrder', direction: 'asc' },
        { field: 'projectDate', direction: 'desc' },
      ],
    },
  ],
  preview: {
    select: {
      date: 'projectDate',
      media: 'coverImage',
      subtitle: 'category',
      title: 'title',
    },
    prepare: ({ date, media, subtitle, title }) => ({
      media,
      subtitle: [subtitle, date?.slice(0, 4)].filter(Boolean).join(' · '),
      title,
    }),
  },
});

export default project;
